// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skoleni.Models;

namespace Skoleni.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Skoleni.Models.Jazyk", b =>
                {
                    b.Property<int>("idJazyka")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nazev");

                    b.HasKey("idJazyka");

                    b.ToTable("seznamJazyku");
                });

            modelBuilder.Entity("Skoleni.Models.Mistnost", b =>
                {
                    b.Property<int>("idMistnosti")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("kapacita");

                    b.Property<string>("nazev");

                    b.HasKey("idMistnosti");

                    b.ToTable("seznamMistnosti");
                });

            modelBuilder.Entity("Skoleni.Models.Skoleni", b =>
                {
                    b.Property<int>("idSkoleni")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nazev");

                    b.Property<string>("popis");

                    b.Property<string>("skolitel");

                    b.HasKey("idSkoleni");

                    b.ToTable("seznamSkoleni");
                });

            modelBuilder.Entity("Skoleni.Models.Termin", b =>
                {
                    b.Property<int>("idTerminu")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("dobaTrvani");

                    b.Property<int?>("jazykidJazyka");

                    b.Property<int?>("skoleniidSkoleni");

                    b.Property<DateTime>("terminKonani");

                    b.HasKey("idTerminu");

                    b.HasIndex("jazykidJazyka");

                    b.HasIndex("skoleniidSkoleni");

                    b.ToTable("seznamTerminu");
                });

            modelBuilder.Entity("Skoleni.Models.Uzivatel", b =>
                {
                    b.Property<int>("idUzivatele")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<int>("idJazyka");

                    b.Property<string>("jmeno");

                    b.Property<string>("prijmeni");

                    b.Property<int>("stredisko");

                    b.HasKey("idUzivatele");

                    b.HasIndex("idJazyka");

                    b.ToTable("seznamUzivatelu");
                });

            modelBuilder.Entity("Skoleni.Models.Termin", b =>
                {
                    b.HasOne("Skoleni.Models.Jazyk", "jazyk")
                        .WithMany()
                        .HasForeignKey("jazykidJazyka");

                    b.HasOne("Skoleni.Models.Skoleni", "skoleni")
                        .WithMany()
                        .HasForeignKey("skoleniidSkoleni");
                });

            modelBuilder.Entity("Skoleni.Models.Uzivatel", b =>
                {
                    b.HasOne("Skoleni.Models.Jazyk", "jazyk")
                        .WithMany()
                        .HasForeignKey("idJazyka")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
